steps:
  # 1. コンテナをビルドする（--no-cache を追加して古い中身を破棄）
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      #'--no-cache', # ★ここに追加：キャッシュを一切使わずビルド
      '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA', 
      '.'
    ]

  # 2. ビルドしたイメージを保存する
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA']

  # 3. Cloud Run にデプロイする
# 3. Cloud Run にデプロイする
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--service-account' # サービスアカウントを指定（コンソールで指定しても上手くいかないため。）
      - 'cloud-build-deployer-for-kinta@slack-kintai-bot-484306.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'FIRESTORE_DB_ID=${APP_ENV}' # DBをdev/prod分離
      - '--memory'
      - '1Gi'          # メモリを 1GB に増強
      - '--cpu'
      - '1'            # CPU 1個をフルに割り当て（起動を速める）
      - '--timeout'
      - '300'          # 起動完了までの待ち時間を 300秒（5分）に延長
      - '--no-cpu-throttling' # CPUを落とさない
      - '--project'         # ★念のため、実行中のプロジェクトIDを明示
      - '${PROJECT_ID}'
      # ------------------

options:
  logging: 'CLOUD_LOGGING_ONLY'