steps:
  # 1. コンテナをビルドする（--no-cache を追加して古い中身を破棄）
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '--no-cache', # ★ここに追加：キャッシュを一切使わずビルド
      '-t', 'gcr.io/$PROJECT_ID/slack-kintai-bot:$COMMIT_SHA', 
      '.'
    ]

  # 2. ビルドしたイメージを保存する
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/slack-kintai-bot:$COMMIT_SHA']

  # 3. Cloud Run にデプロイする
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'slack-kintai-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/slack-kintai-bot:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'

options:
  logging: CLOUD_LOGGING_ONLY